using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System.Linq;
using UnityEngine.SceneManagement;

public class WordsGamePlay : MonoBehaviour
{
    public static WordsGamePlay instance;

    private const int MAX_WORDS = 535;
    string[] English = new string[] {
    "address ",
"attend ",
"reserve",
"construct ",
"cooperate ",
"deliver ",
"educate ",
"invest",
"lead ",
"locate",
"notify ",
"offer ",
"surpass ",
"provide ",
"retain ",
"return",
"issue ",
"charge",
"seek",
"possess",
"announce",
"affect",
"arrange",
"manufacture",
"depart",
"remain",
"approve",
"extend",
"mention",
"contribute",
"renovate",
"express",
"audience",
"confidence ",
"cooperation",
"detour",
"expiration",
"impression",
"lecture",
"investment",
"signature",
"output",
"qualification",
"recognition",
"residence",
"resident",
"study",
"variety",
"procedure",
"expense",
"memorandum",
"newsletter",
"personnel",
"participant",
"subscriber",
"replacement",
"assignment",
"award",
"appointment",
"representative",
"competition",
"accept",
"acknowledge",
"compare",
"consult",
"conduct",
"experience",
"indicate",
"perform",
"predict",
"remind",
"represent",
"respond",
"submit",
"access",
"advise",
"approve",
"complete",
"enforce",
"guarantee",
"imply",
"increase",
"involve",
"prevent",
"purchase",
"raise ",
"repair",
"schedule",
"nominate",
"inspect",
"significant",
"rigorous",
"flexible",
"appropriate",
"defective",
"eligible",
"prosperous",
"qualified",
"steady",
"remarkable",
"specific",
"complicated",
"considerable",
"affordable",
"eager",
"wealthy",
"slightly",
"regularl",
"previously",
"initially",
"markedly",
"nearly",
"exceptionally",
"lately",
"personally",
"rapidly",
"repeatedly",
"respectfully",
"shortly",
"properl",
"substantially",
"precisely",
"widely",
"increasingly",
"currently",
"typically",
"individually",
"unexpectedly",
"generously",
"absolutely.",
"consistently",
"promptly",
"profitable",
"outstanding",
"appropriate",
"thorough",
"wide",
"rigid",
"recent",
"regular",
"spacious",
"qualified",
"abundant",
"permanent",
"dedicated",
"comprehensive",
"emphasize",
"attract",
"depart",
"consider",
"equip",
"fasten",
"fund",
"handle",
"resolve",
"load",
"position",
"register",
"remove",
"reimburse",
"assign",
"accompany",
"instruct",
"track",
"encourage",
"deduct",
"charge",
"appoint",
"obtain",
"propose",
"specialize in",
"merge",
"recover",
"transfer",
"attention",
"cash",
"choice",
"procedure",
"merchandise",
"expertise",
"renovation",
"inquiry",
"location",
"material",
"matter",
"profession",
"profit",
"recipe",
"technician",
"supervisor",
"transaction",
"interruption",
"orientation",
"partner",
"candidate",
"preference",
"instead of",
"look forward to",
"ahead of",
"beyond",
"by means of",
"concerning",
"due to",
"in case of",
"in favor of",
"among",
"throughout",
"on behalf of",
"prior to",
"regardless of",
"during",
"no later than",
"except for",
"in addition to",
"in order to ",
"next to",
"against",
"proposal",
"through",
"across",
"approve",
"authorize",
"specify",
"damage",
"propose",
"interrupt",
"estimate",
"notice",
"pursue",
"postpone",
"maintain",
"revise",
"consult",
"construct",
"contribute",
"undergo",
"organize",
"suggest",
"attach",
"adopt",
"adapt",
"colleague",
"announcement",
"article",
"assistance",
"permission",
"distribution",
"opportunity",
"construction",
"conservation",
"demand",
"critic",
"expansion",
"review",
"appliance",
"accomplishment",
"inspection",
"auditorium",
"headquarters",
"head office",
"reputation ",
"revenue",
"competitor",
"in an effort to",
"in an attempt to",
"in honor of",
"in advance",
"in charge (of)",
"as a result of",
"contrary to",
"in accordance with",
"in response to",
"in terms of",
"on schedule",
"behind schedule",
"ahead of schedule",
"out of order",
"out of stock",
"in compliance with",
"under warranty",
"in celebration of",
"at no cost",
"be looking at",
"be reviewing",
"be holding",
"be writing",
"be pointing",
"be reaching",
"be pouring",
"be filling",
"be sitting",
"be standing",
"be walking",
"be crossing",
"be riding",
"be fixing",
"be carrying",
"be loading",
"be paying for",
"be eating",
"be cleaning",
"be trying on",
"be cooking",
"be checking",
"monitor",
"document",
"rack",
"projector",
"wall",
"ceiling",
"microscope",
"wheel",
"instrument",
"bottle",
"grocery",
"merchandise",
"fabric",
"suitcase",
"meal",
"path",
"plant",
"bridge",
"brick",
"near",
"on the ground",
"one side of",
"outdoors",
"umbrella",
"closet",
"shelf",
"drawer",
"bowl",
"railing",
"light",
"ladder",
"basket",
"lamppost",
"rug",
"vehicle",
"plane",
"harbor",
"dock",
"counter",
"pool",
"deck",
"lake",
"shore",
"patio",
"garage",
"doorway",
"platform",
"track",
"driveway",
"curb",
"intersection",
"gas station",
"in the middle of",
"on the top of",
"above",
"at the back of",
"beneath",
"across from",
"alongside",
"throughout",
"president",
"board members",
"entrepreneur",
"new employee",
"entire staff",
"supervisor",
"coworker",
"keynote speaker",
"assistant",
"secretary",
"representative",
"accountant",
"editor",
"security guard",
"customer",
"volunteer",
"public relations",
"journey",
"disturb",
"department",
"apartment",
"personned ",
"demand",
"slightly",
"shuttle bus",
"complimentary ",
"guest",
"guess",
"landmark",
"operate",
"prohibit",
"corporation",
"affiliated with ",
"pick up",
"recently",
"positive ",
"frequently",
"take place",
"recruit",
"temporary ",
"permanent ",
"branch",
"resign",
"retire",
"insult",
"ceremony ",
"under go",
"renovate",
"maintain",
"executive ",
"representative",
"present",
"loudly",
"take off ",
"immediately",
"implement ",
"break the ice",
"sometime",
"should have",
"take over",
"vendor",
"accommodate",
"offer",
"lobby",
"grand opening ",
"perform",
"apron",
"platform",
"luggage",
"capture ",
"in advance ",
"destination ",
"condition",
"officials",
"submit",
"facility",
"notice ",
"approve",
"tournament",
"banquet",
"by the time ",
"publisher",
"steady",
"heritage ",
"permit",
"access ",
"evidence",
"employment",
"dispose",
"several",
"signature ",
"lecturer",
"curtain ",
"cart",
"stare",
"monitor",
"an effort to",
"plant",
"register ",
"beverage",
"honor ",
"instruct",
"delegates ",
"procedure ",
"surpass",
"fierce",
"thorough",
"throughout (pre)",
"significant",
"entries",
"prolong",
"contract",
"spectators ",
"counter",
"article",
"separate ",
"pond",
"fourtain ",
"extensive ",
"guarantee ",
"fire",
"poseess",
"firt elass",
"economy class",
"conduct",
"modify",
"enforce",
"purchase",
"professionals",
"leather",
"assist",
"confidential",
"intranet",
"mechanical defect",
"donor",
"hesitant",
"spacious",
"discover",
"produce",
"promptly",
"manual",
"issue",
"travel ",
"effective",
"responsible for",
"elevator ",
"itinerary ",
"affordabl",
"personal belonging",
"path",
"pipe",
"stock",
"supplies ",
"crutial",
"contain",
"cautious ",
"be committer",
"out of oder",
"secure ",
"visible ",
"speedy",
"expectations ",
"evaluation ",
"quite",
"quiet",
"results in",
"optimistic ",
"encounter",
"punctual",
"superior to",
"technicain"};
    string[] VietNamese = new string[] {
    "giải quyết/nói chuyện với",
"tham dự",
"đặt chỗ",
"xây dựng",
"hợp tác",
"giao, phân phát",
"giáo dục",
"đầu tư",
"chỉ huy, dẫn dắt",
"đặt",
"thông báo",
"phục vụ, cung cấp",
"vượt qua",
"cung cấp",
"giữ lại",
"trở lại",
"phát hành",
"tính phí",
"tìm kiếm",
"sở hữu",
"loan tin, thông báo",
"có ảnh hưởng đến",
"sắp xếp",
"chế tạo, sản xuất",
"khởi hành",
"duy trì",
"chấp thuận, duyệt",
"mở rộng, kéo dài",
"đề cập đến",
"đóng góp",
"cải tạo, nâng cấp",
"thể hiện, bày tỏ",
"khán giả",
"sự tin tưởng",
"sự hợp tác",
"đường vòng",
"hết hạn",
"ấn tượng",
"bài giảng",
"sự đầu tư",
"chữ ký",
"sản lượng, đầu ra",
"năng lực",
"sự công nhận",
"nơi cư trú",
"người dân",
"nghiên cứu",
"đa dạng",
"thủ tục",
"chi phí",
"thông báo",
"bảng tin",
"nhân sự",
"người tham gia",
"người đăng kí",
"thay thế",
"sự phân công",
"phần thưởng",
"cuộc hẹn",
"người đại diện",
"sự cạnh tranh",
"chấp nhận",
"công nhận",
"so sánh",
"tham khảo ý kiến",
"thực hiện",
"trải qua",
"chỉ ra",
"thi hành",
"dự đoán",
"nhắc nhở",
"đại diện",
"phản ứng",
"gửi đi, nộp",
"truy cập",
"khuyên nhủ",
"chấp thuận",
"hoàn thành",
"thi hành",
"đảm bảo",
"bao hàm, ngụ ý",
"tăng",
"liên quan, đòi hỏi",
"ngăn ngừa",
"mua ",
"tăng, gây quỹ",
"sửa chữa",
"lịch trình",
"đề cử",
"quan sát, kiểm tra",
"đáng kể",
"nghiêm ngặt",
"linh hoạt",
"phù hợp",
"bị lỗi",
"đạt chuẩn, đủ đk",
"thịnh vượng",
"đạt tiêu chuẩn",
"đều đặn",
"đáng chú ý",
"rõ ràng",
"phức tạp",
"đáng kể",
"hợp lý",
"háo hức",
"giàu có",
"không đáng kể",
"thường xuyên",
"trước đây",
"ban đầu",
"rõ rệt",
"gần như",
"đặc biệt",
"gần đây",
"cá nhân, đích thân",
"liên tục",
"nhiều lần",
"trân trọng",
"sớm, chẳng mấy chốc",
"thích hợp",
"đáng kể",
"chính xác",
"rộng rãi",
"ngày càng",
"hiện tại",
"tiêu biểu",
"riêng lẻ, cá nhân",
"bất ngờ",
"rộng lượng",
"tuyệt đối",
"liên tục",
"ngay lập tức",
"có lợi",
"nổi bật",
"hợp lí",
"kỹ lưỡng",
"rộng lớn",
"cứng nhắc",
"gần đây",
"thường xuyên",
"rộng rãi",
"có năng lực",
"dồi dào",
"dài hạn",
"tận tụy",
"toàn diện",
"nhấn mạnh",
"thu hút",
"khởi hành",
"xem xét",
"trang bị",
"thắt chặt",
"tài trợ/quỹ",
"xử lý, giải quyết",
"giải quyết",
"chất lên",
"đặt",
"đăng ký",
"loại bỏ",
"hoàn trả lại",
"phân công",
"đồng hành, hộ tống",
"hướng dẫn",
"theo dõi",
"khuyến khích",
"khấu trừ",
"tính phí",
"bổ nhiệm",
"thu được",
"đề xuất",
"chuyên về",
"hợp nhất, sáp nhập",
"hồi phục",
"chuyển, dời",
"sự chú ý",
"tiền mặt",
"sự lựa chọn",
"thủ tục",
"hàng hóa",
"chuyên môn",
"cải tạo",
"câu hỏi, yêu cầu",
"vị trí",
"nguyên vật liệu",
"vấn đề",
"nghề nghiệp",
"lợi nhuận",
"công thức",
"kỹ thuật viên",
"người giám sát",
"giao dịch",
"sự gián đoạn",
"sự định hướng",
"bạn đồng hành",
"ứng viên",
"sự ưu tiên",
"thay vì, thay cho",
"mong đợi",
"sớm hơn",
"vượt quá",
"bằng cách",
"liên quan đến",
"bởi vì",
"trong trường hợp",
"ủng hộ",
"trong số những",
"trong suốt",
"thay mặt cho",
"trước",
"bất kể",
"trong suốt",
"không muộn hơn",
"ngoại trừ",
"ngoài...ra",
"để mà",
"bên cạnh",
"chống lại",
"đề nghị",
"xuyên qua",
"ngang qua",
"chấp thuận",
"ủy quyền",
"định rõ",
"làm hư hại",
"đề xuất",
"gián đoạn",
"ước tính",
"nhận thấy",
"theo đuổi",
"trì hoãn",
"duy trì",
"chỉnh sửa",
"tham khảo ý kiến",
"xây dựng",
"đóng góp",
"trải qua",
"sắp xếp",
"giới thiệu",
"gắn, đính kèm",
"áp dụng",
"thích nghi",
"đồng nghiệp",
"thông báo",
"bài báo",
"sự giúp đỡ",
"sự cho phép",
"sự phân bổ",
"cơ hội",
"sự xây dựng",
"sự bảo tồn",
"nhu cầu",
"nhà phê bình",
"sự mở rộng",
"sự đánh giá",
"thiết bị",
"thành tựu",
"sự kiểm tra",
"thính phòng",
"trụ sở chính",
"trụ sở chính",
"danh tiếng",
"doanh thu",
"đối thủ",
"trong một nỗ lực để",
"trong một nỗ lực để",
"vinh dự được",
"trước",
"chịu trách nhiệm",
"do, nhờ",
"trái với",
"phù hợp với",
"để đáp lại",
"xét về",
"đúng tiến độ",
"chậm tiến độ",
"trước tiến độ",
"ngưng hoạt động",
"hết hàng",
"phù hợp với",
"được bảo hành",
"để ăn mừng",
"miễn phí",
"đang nhìn",
"đang xem xét",
"được giữ",
"đang viết",
"được trỏ tới ",
"được tiếp cận ",
"được đổ",
"được lấp đầy",
"đang ngồi ",
"đứng",
"được đi bộ",
"được băng qua",
"đang cưỡi",
"đang sửa chữa",
"đang mang",
"đang tải",
"đang trả tiền cho",
"đang ăn",
"đang làm sạch",
"đang thử",
"đang nấu ăn",
"đang kiểm tra",
"màn hình",
"tài liệu",
"giá đỡ",
"máy chiếu",
"tường",
"trần nhà",
"kính hiển vi",
"bánh xe",
"dụng cụ",
"chai",
"tạp hóa",
"hàng hóa",
"sợi vải",
"chiếc vali",
"bữa ăn",
"con đường",
"cây",
"cầu",
"gạch",
"gần",
"trên mặt đất",
"một mặt của",
"ngoài trời",
"chiêc du",
"buồng nhỏ",
"kệ (pl. kệ)",
"ngăn kéo",
"bát",
"lan can",
"soi rọi",
"thang",
"cái rổ",
"cột đèn",
"tấm thảm",
"phương tiện giao thông",
"máy bay",
"hải cảng",
"bến tàu",
"quầy tính tiền",
"hồ bơi",
"boong tàu",
"hồ",
"bờ biển",
"hiên nhà",
"ga-ra",
"ngưỡng cửa",
"nền tảng",
"theo dõi",
"đường lái xe",
"lề đường",
"ngã tư",
"trạm xăng",
"ở giữa",
"trên đỉnh của",
"bên trên",
"ở phía sau của",
"ở trên",
"đối diện với",
"cùng với",
"trong suốt",
"chủ tịch",
"thành viên hội đồng quản trị",
"doanh nhân",
"nhân viên mới",
"toàn bộ nhân viên",
"giám sát viên ",
"đồng nghiệp",
"diễn giả chính",
"phụ tá",
"thư ký",
"tiêu biểu",
"kế toán viên",
"biên tập viên",
"nhân viên bảo vệ",
"khách hàng",
"tình nguyện viên",
"quan hệ công chúng",
"hành trình",
"quấy rầy",
"phòng ban",
"căn hộ",
"phòng nhân sự",
"nhu cầu ",
"nhẹ nhàng",
"xe trung chuyển",
"miễn phí",
"đoán ",
"khách",
"địa điểm lớn",
"vận hành",
"cấm",
"công ty",
"liên kết với ",
"nhặt, nhấc",
"gần đây",
"tích cực",
"thường xuyên",
"diễn ra",
"tuyển dụng",
"ngắn hạn ",
"dài hạn",
"chi nhánh",
"từ chức",
"nghỉ hưu",
"xúc phạm",
"lễ",
"trải qua",
"cải tạo",
"duy trì",
"người điều hành",
"người đại diện",
"trình ra",
"lớn tiếng",
"cất cánh",
"ngay lập tức",
"thực hiện",
"phá bỏ sự e ngại",
"một lúc nào đó",
"lẽ ra nên",
"đảm nhận",
"nhà cung cấp",
"đáp ứng",
"cung cấp",
"tiền sảnh",
"khai trương",
"biểu diễn",
"tạp dề",
"sân ga",
"hành lý",
"bắt giữ",
"trước",
"điểm đến",
"điều kiện",
"chính thức/ quan chức",
"nộp",
"cơ sở, nhà máy",
"thông báo",
"phê duyệt",
"giải đấu",
"yến tiệc",
"trước khi",
"nhà xuất bản",
"đều đặn",
"di sản",
"cho phép",
"sự tiếp cận/đi đến",
"bằng chứng",
"sự tuyển dụng",
"vứt bỏ",
"vài, một số",
"chữ ký",
"giảng viên",
"rèm",
"xe đẩy 4 bánh",
"nhìn chằm chằm",
"màn hình",
"một nỗ lực để ",
"nhà máy",
"đăng ký",
"đồ uống",
"niềm vinh dự",
"hướng dẫn",
"đoàn đại biểu",
"thủ tục",
"vượt qua",
"dữ dội",
"kỹ lưỡng",
"trong suốt (trước)",
"đáng kể",
"bài dự thi",
"kéo dài",
"hợp đồng",
"khán giả",
"quầy",
"bài báo",
"phân chia",
"ao",
"đài phun nước",
"mở rộng",
"đảm bảo",
"sa thải",
"sở hữu",
"hạng thương gia",
"hạng phổ thông",
"thực hiện",
"thay đổi",
"thi hành",
"mua",
"chuyên gia",
"sp bằng sd",
"hỗ trợ",
"riêng tư",
"mạng nội bộ",
"lỗi cơ học",
"nhà tài trợ",
"do dự",
"rộng rãi",
"phát hiện",
"sản xuất",
"ngay đúng lúc",
"sách hướng dẫn",
"vấn đề/số báo",
"đi lại",
"có hiệu lực",
"chịu trách nhiệm",
"thang máy",
"hành trình",
"phải chăng/hợp lý",
"đồ đạc cá nhân",
"đường mòn",
"ống nước",
"chất hàng",
"đồ đạc",
"chủ yếu, cần thiết",
"lưu trữ",
"dè dặt",
"cam kết",
"ngừng hoạt động",
"chắc chắn",
"có thể nhìn thấy",
"nhanh chóng",
"kỳ vọng",
"sự đánh giá",
"khá là ",
"yên tĩnh",
"dẫn đến",
"lạc quan",
"gặp gỡ",
"đúng giờ",
"cao cấp hơn",
"kỹ thuật viên"};
    int[] indexList = new int[MAX_WORDS];

    int point = 0;

    public CanvasGroup scorePanel;

    public Text score;

    private int correct;

    private int currentIndex;

    public GameObject[] box;

    public Text solution;

    void Start()
    {
        if (instance == null)
        {
            instance = this;
        }
        currentIndex = 0;
        System.Random random = new System.Random();
        indexList = Enumerable.Range(0, MAX_WORDS).OrderBy(c => random.Next()).ToArray();
        Spawn();
    }

    public void Spawn()
    {
        correct = indexList[currentIndex];
        if (currentIndex < MAX_WORDS - 1)
        {
            currentIndex++;
        }
        int x = 0;
        int y = 0;
        while (x == correct || y == correct || x == y)
        {
            x = Random.Range(0, MAX_WORDS);
            y = Random.Range(0, MAX_WORDS);
        }
        System.Random random = new System.Random();
        int[] indexBox = Enumerable.Range(0, 3).OrderBy(c => random.Next()).ToArray();
        box[indexBox[0]].GetComponent<Box>().SetString(English[correct], correct);
        box[indexBox[1]].GetComponent<Box>().SetString(English[x], x);
        box[indexBox[2]].GetComponent<Box>().SetString(English[y], y);
        solution.text = VietNamese[correct];
    }
    void ResetPosition()
    {
        for (int i = 0; i < 3; i++)
        {
            box[i].GetComponent<Box>().Restart();
        }
    }
    public void Check(int check)
    {
        if (check == correct)
        {
            point++;
        }
        else
        {
            Time.timeScale = 0;
            scorePanel.alpha = 1;
            scorePanel.blocksRaycasts = true;
            score.text = "SCORE: " + point;
            GameManager.instance.money += (point * 2);
            SaveManager.SaveData();
        }
        ResetPosition();
        Spawn();
    }

    public void Replay()
    {
        LoadSceneManager.instance.LoadScene("WordsScene");
        Time.timeScale = 1;
    }

    public void Home()
    {
        LoadSceneManager.instance.LoadScene("HomeScene");
        Time.timeScale = 1;
    }
}
